table 'DimCentre'
	lineageTag: b8ba599b-9758-5c85-bf53-9389905e9dc5

	column 'center_id'
		dataType: string
		lineageTag: 1974f5f3-003b-5c94-9bd0-7033d922ec90
		summarizeBy: none
		sourceColumn: center_id

		annotation SummarizationSetBy = Automatic

	column 'center_name'
		dataType: string
		lineageTag: 6fa95607-a213-5eb7-9778-8fa071f882f7
		summarizeBy: none
		sourceColumn: center_name

		annotation SummarizationSetBy = Automatic

	column 'city'
		dataType: string
		lineageTag: 1fb0e6a0-5654-5b55-830b-15b1c30f997a
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column 'state'
		dataType: string
		lineageTag: 155edcc0-651a-5b1f-9bda-71dcbd0709c0
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'region'
		dataType: string
		lineageTag: 8cc37f95-f276-54e9-aacf-d5bb85d1d758
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column 'service_bays'
		dataType: int64
		formatString: 0
		lineageTag: 2418997e-41f0-5828-818e-4b095fc0df15
		summarizeBy: none
		sourceColumn: service_bays

		annotation SummarizationSetBy = Automatic

	column 'daily_job_capacity'
		dataType: int64
		formatString: 0
		lineageTag: 98dc7488-f5f5-57b4-b70d-031db55ba317
		summarizeBy: none
		sourceColumn: daily_job_capacity

		annotation SummarizationSetBy = Automatic

	column 'opened_date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b856fb61-1e11-59ac-9f51-e8aea4b18b09
		summarizeBy: none
		sourceColumn: opened_date

		annotation SummarizationSetBy = Automatic

	partition 'DimCentre' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "service_centers.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"center_id", type text}, {"center_name", type text}, {"city", type text}, {"state", type text}, {"region", type text}, {"service_bays", Int64.Type}, {"daily_job_capacity", Int64.Type}, {"opened_date", type date}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
