table 'part_usage'
	lineageTag: 862bb5a5-4998-507e-b8bf-0e894d5fbba4

	column 'usage_id'
		dataType: string
		lineageTag: da1c2d91-bb4e-5ad2-a003-1f8ceb0d8337
		summarizeBy: none
		sourceColumn: usage_id

		annotation SummarizationSetBy = Automatic

	column 'work_order_id'
		dataType: string
		lineageTag: db147164-3354-5fd5-ac8c-7749f3cd2d24
		summarizeBy: none
		sourceColumn: work_order_id

		annotation SummarizationSetBy = Automatic

	column 'part_id'
		dataType: string
		lineageTag: 4b880375-d9cf-51a8-ac7b-d75172177473
		summarizeBy: none
		sourceColumn: part_id

		annotation SummarizationSetBy = Automatic

	column 'quantity'
		dataType: int64
		formatString: 0
		lineageTag: ef2341a0-fd6d-587b-b44b-657186607290
		summarizeBy: none
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	partition 'part_usage' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "part_usage.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"usage_id", type text}, {"work_order_id", type text}, {"part_id", type text}, {"quantity", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
