table 'parts'
	lineageTag: 7a68b3e2-5093-5041-86bb-49007d956f12

	column 'part_id'
		dataType: string
		lineageTag: 430ff95a-4c19-5b6b-9583-2100869737b7
		summarizeBy: none
		sourceColumn: part_id

		annotation SummarizationSetBy = Automatic

	column 'part_name'
		dataType: string
		lineageTag: 542f1fc9-a3f5-56dc-9c70-f514022fe8fc
		summarizeBy: none
		sourceColumn: part_name

		annotation SummarizationSetBy = Automatic

	column 'part_category'
		dataType: string
		lineageTag: f66590bf-aa07-5330-aa59-4c4afa677ae4
		summarizeBy: none
		sourceColumn: part_category

		annotation SummarizationSetBy = Automatic

	column 'compatible_models'
		dataType: string
		lineageTag: 18a1b9fa-d128-5b15-a366-e2a96a063ab3
		summarizeBy: none
		sourceColumn: compatible_models

		annotation SummarizationSetBy = Automatic

	column 'unit_cost'
		dataType: double
		formatString: #,0.00
		lineageTag: a1bb49ef-51da-5781-9681-3e6a6f1b6820
		summarizeBy: none
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column 'supplier_lead_days'
		dataType: int64
		formatString: 0
		lineageTag: aaad47ce-657c-538f-bcf0-28e848a05434
		summarizeBy: none
		sourceColumn: supplier_lead_days

		annotation SummarizationSetBy = Automatic

	partition 'parts' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "parts.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"part_id", type text}, {"part_name", type text}, {"part_category", type text}, {"compatible_models", type text}, {"unit_cost", type number}, {"supplier_lead_days", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
